language: php
sudo: required

services:
  - mysql
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - mysql -e 'create database osm_auth;'
  - composer install

script:
  - ./scripts/config.sh
  - phpunit --configuration tests/php/phpunit.xml
