---
- name: Get common software properties
  apt: name=software-properties-common state=present

- name: Add HHVM repo
  apt_repository:
    repo: "deb http://dl.hhvm.com/ubuntu trusty main"
    state: present
    update_cache: yes

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - build-essential
    - tcl8.5
    - nginx
    - mysql-server
    - hhvm
    - python-dev
    - python-pip
    - libmysqlclient-dev
    - redis-server
  notify:
    - restart mysql
    - restart redis
    - restart nginx
    - restart hhvm

- name: Add nginx config
  copy: src=default dest=/etc/nginx/sites-available/default mode=0644
  notify:
    - restart nginx

- name: Install pip packages
  pip: name=MySQL-python

- name: Start services
  service: name={{ item }} state=started
  with_items:
    - nginx
    - redis-server
    - mysql
    - hhvm

- name: Add MySQL user
  mysql_user:
    login_user: root
    login_password: ""
    name: osm
    password: osm
    priv: "*.*:ALL,GRANT"
    state: present

- name: Add MySQL database
  mysql_db:
    name: osm_auth
    state: present
    login_user: osm
    login_password: osm

- name: Add MySQL user table
  mysql_db:
    name: osm_auth
    state: import
    target: /vagrant/schemas/users.sql

- name: Create app config directory
  file: path=/etc/osm state=directory

- name: Add app config
  copy: src=conf.ini dest=/etc/osm/conf.ini mode=0644

- name: Check existing app directory
  stat: path=/usr/share/nginx/html
  register: app_dir

- name: Remove existing app directory
  file: path=/usr/share/nginx/html state=absent
  when: app_dir.stat.exists == True

- name: Symlink root html folder with app directory
  file: dest=/usr/share/nginx/html src=/vagrant/httpdocs state=link force=yes

- name: Run HHVM setup script
  command: sudo /usr/share/hhvm/install_fastcgi.sh
  notify:
    - restart nginx
    - restart hhvm
